export type CreatureEntry = {
  name: string;
  mythos_background: string;
  san_loss_success: string;
  san_loss_failure: string;
  str: number | null;
  con: number | null;
  pow: number | null;
  dex: number | null;
  siz: number | null;
  hp: number | null;
  mp: number | null;
  armor: string | null;
  attacks: string | null;
  can_use_spells: boolean;
  notes: string | null;
  category: string;
};

export const CREATURE_CATALOG: CreatureEntry[] = [
  // 海洋系
  {
    name: "ディープワン",
    mythos_background: "ダゴンとヒュドラに仕える海底の種族。人間と交わることで混血を生む。イア！ダゴン！イア！ヒュドラ！",
    san_loss_success: "0",
    san_loss_failure: "1D6",
    str: 75,
    con: 65,
    pow: 75,
    dex: 50,
    siz: 65,
    hp: 13,
    mp: 15,
    armor: "1点（鱗）",
    attacks: "爪1D6、咬み1D4+1D4",
    can_use_spells: true,
    notes: "水中では動きが速く、地上では動きが鈍い。陸海両方で生活できる。",
    category: "海洋系",
  },
  {
    name: "ダゴン",
    mythos_background: "深きものどもの神父にして守護者。太古の昔から海の底に潜む巨大な神格的存在。",
    san_loss_success: "1D6",
    san_loss_failure: "1D20",
    str: 300,
    con: 200,
    pow: 100,
    dex: 30,
    siz: 300,
    hp: 100,
    mp: 20,
    armor: "3点（神格的な体）",
    attacks: "爪3D6+ダメージボーナス、踏みつけ4D6",
    can_use_spells: true,
    notes: "海域か沿岸部のみに出現する。存在を目撃するだけで正気を蝕む。",
    category: "海洋系",
  },
  // 宇宙系
  {
    name: "ショゴス",
    mythos_background: "旧支配者が万能の使役生物として作り出した原形質の怪物。「テケリ・リ！テケリ・リ！」と叫ぶ。",
    san_loss_success: "1D10",
    san_loss_failure: "1D100",
    str: 200,
    con: 200,
    pow: 30,
    dex: 50,
    siz: 100,
    hp: 60,
    mp: 6,
    armor: "2点（変形する体、物理ダメージ半減）",
    attacks: "殴打4D6（一つの攻撃で二人を同時に攻撃できる）",
    can_use_spells: false,
    notes: "炎と電気に弱い。巨大で洞窟や狭い場所では身を屈める必要がある。",
    category: "宇宙系",
  },
  {
    name: "バイアクヒー",
    mythos_background: "宇宙空間を飛ぶ旧支配者の使い魔。ハスターの召喚に使われる飛翔する生物。",
    san_loss_success: "0",
    san_loss_failure: "1D6",
    str: 75,
    con: 70,
    pow: 50,
    dex: 60,
    siz: 80,
    hp: 15,
    mp: 10,
    armor: null,
    attacks: "爪1D3+ダメージボーナス、咬み1D6",
    can_use_spells: false,
    notes: "召喚されることが多い。搭乗可能（POW対抗ロールに成功すれば）。",
    category: "宇宙系",
  },
  {
    name: "ミ=ゴ",
    mythos_background: "冥王星（ユゴス）から来た真菌状の異星人。地球の鉱石を採掘するために来訪している。",
    san_loss_success: "0",
    san_loss_failure: "1D6",
    str: 60,
    con: 60,
    pow: 65,
    dex: 75,
    siz: 55,
    hp: 12,
    mp: 13,
    armor: "なし（部分的甲皮1点）",
    attacks: "爪1D6、電気兵器2D6（先端技術）",
    can_use_spells: true,
    notes: "人間の脳を生きたまま金属容器に保存する技術を持つ。光に弱い写真には映らない。",
    category: "宇宙系",
  },
  {
    name: "スター・スポーン・オブ・クトゥルフ",
    mythos_background: "クトゥルフが地球に連れてきた眷属。巨大な蛸頭の翼を持つ宇宙的存在。",
    san_loss_success: "1D10",
    san_loss_failure: "1D100",
    str: 200,
    con: 200,
    pow: 100,
    dex: 50,
    siz: 200,
    hp: 40,
    mp: 20,
    armor: "4点（宇宙的な体）",
    attacks: "触手3D6、踏みつけ4D6",
    can_use_spells: true,
    notes: "本物のクトゥルフではなく眷属。それでも小規模シナリオでは全滅の危険がある。",
    category: "宇宙系",
  },
  {
    name: "グレート・レース・オブ・イス",
    mythos_background: "時間と空間を超えて意識を転送できる太古の種族。かつて地球を支配していた。",
    san_loss_success: "0",
    san_loss_failure: "1D6",
    str: 80,
    con: 80,
    pow: 95,
    dex: 40,
    siz: 100,
    hp: 18,
    mp: 19,
    armor: "なし",
    attacks: "稲妻銃3D10（稲妻銃は金属製で再充電可能）",
    can_use_spells: true,
    notes: "過去・未来の知識を持つ。交渉が可能な場合もある。",
    category: "宇宙系",
  },
  // 次元外系
  {
    name: "ハウンド・オブ・ティンダロス",
    mythos_background: "「曲線」ではなく「角」から来る時空の狩人。一度獲物を認識すると執拗に追跡する。",
    san_loss_success: "1D6",
    san_loss_failure: "1D20",
    str: 40,
    con: 40,
    pow: 100,
    dex: 60,
    siz: 40,
    hp: 8,
    mp: 20,
    armor: "なし",
    attacks: "爪1D6+1D6（毒：STRロール失敗で1D6追加ダメージ）",
    can_use_spells: false,
    notes: "直角のある場所からしか現れない。丸い部屋に隠れると侵入できない。",
    category: "次元外系",
  },
  {
    name: "ナイトゴーント",
    mythos_background: "夢の国の番人。翼を持つ黒い無貌（顔のない）の生物。声を立てない。",
    san_loss_success: "0",
    san_loss_failure: "1D3",
    str: 60,
    con: 65,
    pow: 50,
    dex: 65,
    siz: 65,
    hp: 13,
    mp: 10,
    armor: "なし",
    attacks: "掴み（1ラウンドに特殊：掴まれた対象はくすぐられ行動不能になる）",
    can_use_spells: false,
    notes: "夢の国でよく遭遇する。ノーデンスに従う。対話は不可能だが命令に従わせることができる。",
    category: "次元外系",
  },
  {
    name: "ファイア・ヴァンパイア",
    mythos_background: "炎の形を持つ異次元の存在。フォモールの仔とも呼ばれる。星から落ちてくる炎。",
    san_loss_success: "0",
    san_loss_failure: "1D4",
    str: 15,
    con: 25,
    pow: 50,
    dex: 65,
    siz: 10,
    hp: 5,
    mp: 10,
    armor: "物理攻撃無効（炎の体）",
    attacks: "接触で2D6の炎ダメージ（毎ラウンド）",
    can_use_spells: false,
    notes: "水や冷気に弱い。1体あたりのHPは低いが複数で来ることが多い。",
    category: "次元外系",
  },
  // 眷属・使い魔
  {
    name: "ダーク・ヤング・オブ・シュブ＝ニグラス",
    mythos_background: "千の仔を産む山羊であるシュブ＝ニグラスの産み落とした暗黒の眷属。巨大な木の怪物のような姿。",
    san_loss_success: "1D6",
    san_loss_failure: "1D20",
    str: 120,
    con: 120,
    pow: 50,
    dex: 40,
    siz: 120,
    hp: 24,
    mp: 10,
    armor: "3点（暗黒の肉体）",
    attacks: "触手2D6×2（一度に2回攻撃）、踏みつけ1D8+ダメージボーナス",
    can_use_spells: false,
    notes: "森や野外でのみ召喚可能。神を信仰する者を特に敵視する傾向がある。",
    category: "眷属",
  },
  {
    name: "フォームレス・スポーン",
    mythos_background: "ツァトゥグァの黒き落とし子。不定形の暗黒物質で、どんな形にも変形できる。",
    san_loss_success: "0",
    san_loss_failure: "1D8",
    str: 60,
    con: 60,
    pow: 65,
    dex: 60,
    siz: 80,
    hp: 14,
    mp: 13,
    armor: "2点（不定形の体）",
    attacks: "打撃1D6+1D6、絡みつき（逃れるにはSTR対抗）",
    can_use_spells: false,
    notes: "炎と電気には通常ダメージを受ける。ツァトゥグァの神殿の守護者として使われることが多い。",
    category: "眷属",
  },
  {
    name: "サーヴィタ",
    mythos_background: "旧支配者に仕えるために作られた小型の従者。様々な素材から呪術的に生成される。",
    san_loss_success: "0",
    san_loss_failure: "1D4",
    str: 20,
    con: 20,
    pow: 50,
    dex: 65,
    siz: 15,
    hp: 4,
    mp: 10,
    armor: "なし",
    attacks: "爪1D4、咬み1D3",
    can_use_spells: false,
    notes: "単独では弱いが群れで来ることが多い。作成した術者の命令のみに従う。",
    category: "眷属",
  },
  // 不死系
  {
    name: "グール",
    mythos_background: "墓場や地下に潜む屍肉食らい。人間が堕落して変化したともいわれる異形の存在。",
    san_loss_success: "0",
    san_loss_failure: "1D6",
    str: 80,
    con: 80,
    pow: 65,
    dex: 50,
    siz: 75,
    hp: 16,
    mp: 13,
    armor: "なし",
    attacks: "爪1D6、咬み1D4+2（咬みによる感染の可能性あり）",
    can_use_spells: true,
    notes: "地下通路やトンネルに詳しい。交渉が可能な場合もある。グールに噛まれると変性のリスクがある。",
    category: "不死系",
  },
  {
    name: "ゾンビ",
    mythos_background: "黒魔術によって蘇らせられた死者。痛みを感じず疲れ知らずで動き続ける不死の肉体。",
    san_loss_success: "0",
    san_loss_failure: "1D6",
    str: 80,
    con: 80,
    pow: 5,
    dex: 25,
    siz: 65,
    hp: 20,
    mp: 1,
    armor: "1点（死体の体）",
    attacks: "殴打1D8+ダメージボーナス",
    can_use_spells: false,
    notes: "頭部破壊か焼却で完全に倒せる。低いPOWのため呪文はほぼ使えない。作成には「クリエイト・ゾンビ」呪文が必要。",
    category: "不死系",
  },
  {
    name: "ゴースト",
    mythos_background: "強い執念を持って現世に留まる死者の霊魂。生前の場所や関係者の近くに出現する。",
    san_loss_success: "1D3",
    san_loss_failure: "1D10",
    str: null,
    con: null,
    pow: 80,
    dex: 50,
    siz: null,
    hp: null,
    mp: 16,
    armor: "物理攻撃無効（霊体）",
    attacks: "精神攻撃（POW対抗ロール失敗で一時的狂気）",
    can_use_spells: false,
    notes: "物理攻撃は無効。魔術か電磁波系の攻撃、または成仏させることで排除できる。",
    category: "不死系",
  },
];

export const CREATURE_CATEGORIES = [
  "すべて",
  "海洋系",
  "宇宙系",
  "次元外系",
  "眷属",
  "不死系",
] as const;
