export type MythosCreature = {
  name: string;
  origin: string;
  str: number | null;
  con: number | null;
  pow: number | null;
  dex: number | null;
  siz: number | null;
  hp: number | null;
  mp: number | null;
  armor: string | null;
  san_loss_success: string;
  san_loss_fail: string;
  attacks: string[];
  notes: string | null;
};

export const MYTHOS_CREATURES: MythosCreature[] = [
  {
    name: "グール",
    origin: "ラヴクラフト作品全般",
    str: 80,
    con: 65,
    pow: 45,
    dex: 60,
    siz: 65,
    hp: 13,
    mp: 9,
    armor: null,
    san_loss_success: "0/1d3",
    san_loss_fail: "1/1d6",
    attacks: ["爪 2回: 1d6+1d4", "噛みつき 1回: 1d6+1d4"],
    notes: "暗闇での視力あり。死体を食べる。墓場や地下に生息。",
  },
  {
    name: "ゾンビ",
    origin: "魔術師による死者蘇生",
    str: 80,
    con: 80,
    pow: 5,
    dex: 25,
    siz: 65,
    hp: 15,
    mp: 1,
    armor: "1（皮膚の厚さ）",
    san_loss_success: "0/1d3",
    san_loss_fail: "1/1d8",
    attacks: ["殴打 1回: 1d6+1d6"],
    notes: "痛みを感じない。火に弱い。知性なし。魔術師の命令に従う。",
  },
  {
    name: "ディープ・ワン",
    origin: "インスマスの影（ラヴクラフト）",
    str: 100,
    con: 65,
    pow: 65,
    dex: 50,
    siz: 80,
    hp: 15,
    mp: 13,
    armor: "1（鱗）",
    san_loss_success: "0/1d4",
    san_loss_fail: "1/1d6+2",
    attacks: ["爪 2回: 1d6+1d4", "噛みつき 1回: 1d4"],
    notes: "陸・海両生。ダゴン・ハイドラを崇拝。人間との混血「インスマス面相」が存在する。",
  },
  {
    name: "クトゥルフ（神格）",
    origin: "クトゥルフの呼び声（ラヴクラフト）",
    str: 800,
    con: 500,
    pow: 300,
    dex: 30,
    siz: 500,
    hp: 100,
    mp: 60,
    armor: "火器・爆発物無効（近接のみ1d6）",
    san_loss_success: "1d10/1d100",
    san_loss_fail: "2d20/1d100",
    attacks: ["踏みつぶし: 10d6", "触手: 2d6"],
    notes: "R'lyehで眠る。死すことなし（倒しても再生）。テレパシーで夢に侵入。",
  },
  {
    name: "ショゴス",
    origin: "狂気の山脈にて（ラヴクラフト）",
    str: 300,
    con: 200,
    pow: 100,
    dex: 10,
    siz: 300,
    hp: 50,
    mp: 20,
    armor: "武器無効（火のみ有効）",
    san_loss_success: "1d10/1d100",
    san_loss_fail: "2d10/1d100",
    attacks: ["強打・押しつぶし: 2d6+2d6"],
    notes: "原古代種族の奴隷生物。擬似目・擬似口を作れる。炎と電撃が有効。",
  },
  {
    name: "ハウンド・オブ・ティンダロス",
    origin: "ティンダロスの猟犬（フランク・ロング）",
    str: 100,
    con: 80,
    pow: 100,
    dex: 150,
    siz: 60,
    hp: 14,
    mp: 20,
    armor: null,
    san_loss_success: "1/1d6",
    san_loss_fail: "1d6/1d20",
    attacks: ["舌による攻撃: 2d6+猛毒"],
    notes: "角度のある場所（壁の角・コーナー）から出現。丸みのある空間には来られない。時間の歪みを追う。",
  },
  {
    name: "バイアクヘー（星の戦士）",
    origin: "イエンツのイエン（アウグスト・デアレス）",
    str: 65,
    con: 80,
    pow: 65,
    dex: 65,
    siz: 65,
    hp: 15,
    mp: 13,
    armor: null,
    san_loss_success: "0/1d3",
    san_loss_fail: "1/1d6",
    attacks: ["爪 2回: 1d6+1d4", "噛みつき 1回: 1d6+1d4"],
    notes: "翼を持つ。騎乗生物として使役される。ハスター（邪神）と関連。",
  },
  {
    name: "ナイトゴーント",
    origin: "ラヴクラフト作品全般",
    str: 90,
    con: 65,
    pow: 45,
    dex: 80,
    siz: 65,
    hp: 13,
    mp: 9,
    armor: null,
    san_loss_success: "0/1d3",
    san_loss_fail: "1/1d6",
    attacks: ["爪 2回: 1d3+1d4（ガードル攻撃）"],
    notes: "顔のない飛行生物。笑わせない（くすぐる）。地球の「夢の国」の番人。",
  },
  {
    name: "ミ＝ゴ（ユゴスの菌類）",
    origin: "囁く者（ラヴクラフト）",
    str: 80,
    con: 65,
    pow: 80,
    dex: 80,
    siz: 65,
    hp: 13,
    mp: 16,
    armor: "1（甲殻）",
    san_loss_success: "0/1d4",
    san_loss_fail: "1/1d6",
    attacks: ["爪 2回: 1d3+1d4"],
    notes: "鉱物採掘が目的。高度な外科技術（脳の摘出・保存）。電気でダメージを受ける。",
  },
  {
    name: "火炎放射体（フレイム・ウォーカー）",
    origin: "神話全般",
    str: 60,
    con: 80,
    pow: 65,
    dex: 60,
    siz: 60,
    hp: 14,
    mp: 13,
    armor: "火器無効（物理のみ）",
    san_loss_success: "0/1d4",
    san_loss_fail: "1/1d8",
    attacks: ["炎放射: 3d6（火傷）"],
    notes: "炎でできた存在。水が有効。物理武器は半減。",
  },
  {
    name: "ハスター（邪神）",
    origin: "ビアース/デアレス",
    str: 500,
    con: 500,
    pow: 300,
    dex: 25,
    siz: 400,
    hp: 100,
    mp: 60,
    armor: "武器無効",
    san_loss_success: "1d10/1d100",
    san_loss_fail: "2d10/1d100",
    attacks: ["触手: 3d6", "存在の圧力: SANチェック"],
    notes: "黄のしるし（イエローサイン）で喚び出せる。双子の戦いを嫌う（クトゥルフと対立）。",
  },
  {
    name: "ニャルラトホテプ（這い寄る混沌）",
    origin: "ラヴクラフト作品全般",
    str: 200,
    con: 200,
    pow: 500,
    dex: 100,
    siz: 200,
    hp: 40,
    mp: 100,
    armor: "武器無効",
    san_loss_success: "1d6/1d20",
    san_loss_fail: "1d20/1d100",
    attacks: ["触手: 5d6", "精神攻撃: POW対抗"],
    notes: "千の仮面を持つ。人間に姿を変えて現れる。外神のメッセンジャー。多数の化身がある。",
  },
  {
    name: "ンガク（暗黒ファラオ）",
    origin: "エジプト神話/ラヴクラフト",
    str: 65,
    con: 80,
    pow: 100,
    dex: 80,
    siz: 65,
    hp: 15,
    mp: 20,
    armor: null,
    san_loss_success: "1/1d6",
    san_loss_fail: "1d6/1d20",
    attacks: ["魔術攻撃: POW対抗", "短剣: 1d4+1d4"],
    notes: "ニャルラトホテプの化身の一つ。エジプトを支配した暗黒の王。",
  },
  {
    name: "サーペント・ピープル（蛇人間）",
    origin: "コナン伝説（ハワード）/クトゥルフ神話",
    str: 65,
    con: 65,
    pow: 65,
    dex: 80,
    siz: 65,
    hp: 13,
    mp: 13,
    armor: "1（鱗）",
    san_loss_success: "0/1d4",
    san_loss_fail: "1/1d6",
    attacks: ["爪 2回: 1d3+1d4", "噛みつき（毒）: 1d3+毒"],
    notes: "人間に変身できる。魔術を使う。イグ（蛇神）を崇拝。",
  },
  {
    name: "チョー・チョー（人食い虫）",
    origin: "ラヴクラフト/ダーレス",
    str: 30,
    con: 45,
    pow: 25,
    dex: 90,
    siz: 15,
    hp: 6,
    mp: 5,
    armor: null,
    san_loss_success: "0/1d2",
    san_loss_fail: "1/1d4",
    attacks: ["噛みつき（集団攻撃）: 1d2×体数"],
    notes: "群れで行動。人の顔の特徴を記憶して変身模倣。",
  },
  {
    name: "ダゴン",
    origin: "ダゴン（ラヴクラフト）",
    str: 400,
    con: 200,
    pow: 100,
    dex: 30,
    siz: 400,
    hp: 60,
    mp: 20,
    armor: "1d6（魚類の鱗）",
    san_loss_success: "1d6/2d10",
    san_loss_fail: "2d6/2d20",
    attacks: ["巨大な爪: 3d6", "踏みつぶし: 2d6"],
    notes: "ディープ・ワンの神。海中に住む。インスマスの神殿で崇拝される。",
  },
  {
    name: "旧支配者の星の落とし子",
    origin: "ラヴクラフト作品",
    str: 80,
    con: 80,
    pow: 80,
    dex: 80,
    siz: 50,
    hp: 16,
    mp: 16,
    armor: null,
    san_loss_success: "0/1d4",
    san_loss_fail: "1/1d6",
    attacks: ["分裂: 無限増殖（細胞分裂）", "溶解液: 1d6"],
    notes: "単細胞生命体。細胞分裂で増殖。電気が有効。",
  },
  {
    name: "イット（地獄の存在）",
    origin: "シュマゴラス関連",
    str: 200,
    con: 100,
    pow: 100,
    dex: 50,
    siz: 100,
    hp: 30,
    mp: 20,
    armor: "1d6",
    san_loss_success: "1d6/2d10",
    san_loss_fail: "2d6/2d20",
    attacks: ["触肢: 1d6+1d6×本数"],
    notes: "タコ状の奇怪な姿。シュマゴラスに仕える。強力な精神攻撃。",
  },
  {
    name: "月の獣",
    origin: "幻夢境の探求（ラヴクラフト）",
    str: 100,
    con: 80,
    pow: 80,
    dex: 60,
    siz: 80,
    hp: 16,
    mp: 16,
    armor: null,
    san_loss_success: "0/1d6",
    san_loss_fail: "1d3/2d10",
    attacks: ["爪 2回: 1d6+1d4", "精神攻撃: POW対抗"],
    notes: "夢の国に生息。月から来る巨大な白い半霊的存在。知性を持つ。",
  },
  {
    name: "古のもの（エルダー・シング）",
    origin: "狂気の山脈にて（ラヴクラフト）",
    str: 200,
    con: 100,
    pow: 80,
    dex: 50,
    siz: 150,
    hp: 30,
    mp: 16,
    armor: "1d6（厚い皮膚）",
    san_loss_success: "1/1d6",
    san_loss_fail: "1d6/1d20",
    attacks: ["触手: 1d6+1d6"],
    notes: "真に古い存在。ショゴスを作り出した。飛行可能。水中でも生活できる。南極に存在。",
  },
];
